application/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    title = StringField('Título', validators=[
                        DataRequired(), Length(min=4, max=120)])
    content = TextAreaField('Mensagem', validators=[
                            DataRequired(), Length(min=20, max=10000)])
    submit = SubmitField('Publicar')

application/main/routes.py
from flask import render_template, request, Blueprint, flash
from application.models import Post

# Veja que cada diretório sua configuração local posts=posts; users=users;
# main=main

main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'], defaults={"page": 1})
@main.route('/<int:page>', methods=['GET', 'POST'])
def index(page):
    page = page
    pages = 5
    posts = Post.query.order_by(
        Post.date_posted.desc()).paginate(page, pages, error_out=False)
    if request.method == 'POST' and 'tag' in request.form:
        tag = request.form["tag"]
        search = "%{}%".format(tag)
        posts = Post.query.filter(Post.title.like(search)).paginate(
            per_page=pages, error_out=False)
        result = Post.query.filter(Post.title.like(search)).count()
        flash(f"A pesquisa encontrou {result} resultado.", 'info')

        return render_template('index.html', posts=posts, tag=tag)

    return render_template('index.html', posts=posts, title='Painel Principal')


@main.route('/about')
def about():
    return render_template('about.html', title='Sobre')

application/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from application import db, app
from application.models import Post
from application.posts.forms import PostForm

# Veja que cada diretório sua configuração local posts=posts; users=users

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Conteúdo publicado com sucesso!', 'success')
        return redirect(url_for('main.index'))
    return render_template('posting.html', title='Novas Postagens',
                           form=form, legend='Nova Postagem')

# rota para verificar o acesso do usuário ao post específico


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


# rota para modificar o post
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)  # criar página de erro.
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Postagem atualizada com sucesso!", 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('posting.html',
                           title='Alterando Informações da Postagem',
                           form=form, legend='Alterar Informações')

# Rota para excluir o post


@posts.route("/post/<int:post_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)  # criar página de erro.
    db.session.delete(post)
    db.session.commit()
    flash("Postagem deletada com sucesso!", 'success')
    return redirect(url_for('main.index'))

application/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from application import db, bcrypt
from application.models import User, Post
from application.users.forms import (RegistrationForm, LoginForm,
                                     UpdateAccountForm,
                                     RequestResetForm, ResetPasswordForm)
from application.users.utils import save_picture, send_reset_email

# Blueprint será utilizado para modularizar, geralmente
# aplicado para projetos maiores, separando os mesmo em fragmentos.
# A principal função dele aqui será uma rota local,
# não utilizando mais a variável global, mas variável para o diretório users
# Esse users é aplicado para qualquer tipo de variável
# que tenha dentro do projeto

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Conta criada com sucesso! Você já pode efetuar o login',
              'success')

        return redirect(url_for('users.login'))

    return render_template('register.html', title='Cadastrar', form=form)

# acessar conta (login)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f'Seja Bem vindo ao Direito Sem Preconceito {user.username}',
                  'success')
            return redirect(next_page) if next_page \
                else redirect(url_for('main.index'))

        else:
            flash('Não foi possível acessar sua conta.\
                Por favor verifique seu email e senha', 'danger')
    return render_template('login.html', title='Entrar', form=form)

# rota para sair do users


@users.route('/logout')
def logout():
    logout_user()
    flash('Você acabou de desconectar da sessão.', 'warning')
    return redirect(url_for('main.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Perfil atualizado com sucesso!", 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)

    return render_template('account.html', title='Conta',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


# rota requisição de troca de senha (vai gerar um token 30min)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("Acabamos de enviar um e-mail com instruções\
              para que você possa efetuar sua alteração de senha.", 'info')
        return redirect(url_for('users.login'))
    return render_template('request_reset_pass.html', form=form,
                           title='Mudando Senha')


# rota para utilizar o POST e aplicar a alteração da senha
@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash("Sua solicitação de troca de senha expirou.\
              Faça uma nova requisição!", 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Você acabou de mudar sua senha com sucesso!',
              'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form,
                           title='Mudando Senha')

application/templates/about.html
{%extends "layout.html"%}

{%block content%}
<div class="content-section">
<h1>Sobre o site</h1><br>

<h4>O que é o DSP?</h4>
    
<p class="text-justify">A sigla significa Direito Sem Preconceito, que venho de um propósito de oferecer um espaço aberto para acadêmicos do curso de direito trocarem informações práticas em relação aos estudos feitos em aula, e suas experiências fora de aula, tornando assim um ambiente propício para os acadêmicos desenvolverem seu espírito de equipe e liderença.</p><br>

<h4>Objetivo</h4>

<p class="text-justify">Pois bem, o "Direito Sem Preconceito" venho para destravar sua mente, levar você a outra era, a era do compartilhamento mútuo e amigável, condicionando todos evoluirem juntos,  sem preconceito com liturgias, correntes doutrinárias ou políticas, um ambiente ideal para você evoluir e levar seu colega junto.</p><br>

<h4>Ferramentas</h4>

<p class="text-justify">
    
    <ol>
        <li class="margin-top">
           <strong> Blog Post:</strong> sistema para compartilhar informações e visualizar informações dos colegas.</li>
        <li class="margin-top">
           <strong> Pesquisa: </strong> sistema para você pesquisar postagens ou perfis específicos do seu interesse.</li>
        <li class="margin-top ">
           <strong> Peticionamento: </strong> sistema com inteligência para oferecer uma tese e todo quadro para o acadêmico desenvolver a petição</li>
    </ol>
</p>
</div>

{%endblock%}

application/templates/account.html
{%extends "layout.html"%} {%block content%}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <p class="text-secondary">{{ current_user.email }}</p>
    </div>
  </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.picture.label() }}
          {{ form.picture(class="form-control-file") }}
          {% if form.picture.errors %}
              {% for error in form.picture.errors %}
                  <span class="text-danger">{{ error }}</span></br>
              {% endfor %}
          {% endif %}
        </div>
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Informações do Perfil</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{%endblock%}

application/templates/index.html
{%extends "layout.html"%}

{%block content%}
  {% for post in posts.items %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%y- %H:%M') }}</small>
      </div>
      <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  {%endfor %}
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}

    
{%endblock content%}

application/templates/layout.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="{{url_for('static', filename='imagens/icon_DSP.png')}}" rel="icon">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    {% if title %}
    <title> Direito Sem Preconceito - {{ title }}</title> <!--Atualizador de sub-titulo-->
    {% else %}
    <title>Direito Sem Preconceito</title>
    {% endif %}    

</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/"> <img src="{{url_for('static', filename='imagens/DSPf.png')}}" alt=""> </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.index') }}"><i class="far fa-list-alt"></i><span> Painel Principal</span></a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}"><i class="far fa-question-circle"></i><span> Sobre</span></a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  <form action="" method="POST" autocomplete="off" class="form-inline">
                  <input type="text" class="form-control mr-sm-2" name="tag" id="tag" placeholder="Palavra chave">
                  <input type="submit"  value="Pesquisar" class="btn btn-outline-light my-2 my-sm-0" name="">
                  </form>
                    <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}"> <i class="far fa-comments"></i><span> Post</span></a>
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}"><i class="fas fa-user-cog"></i><span> Perfil</span></a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}"
                        ><i class="fas fa-power-off"></i><span> Sair</span></a
                      >
                {% else %}
                
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}"><i class="fas fa-user-check"></i><span> Entrar</span></a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}"><i class="fas fa-user-plus"></i><span> Criar conta</span></a>
                  {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            <!--obter as mensagens enviadas para esse template. Esse with_categories obterá a categorai 'success-->
            {% with messages = get_flashed_messages(with_categories=true) %} 
              {% if messages %}
                {% for category, message in messages%}
                   <div class="alert alert-{{category}}">
                     {{message}}
                   </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
          {% if current_user.is_authenticated %}
          <div class="col-md-4">
            <div class="content-section">
              <h3>Fique Por Dentro!</h3>
              <p class='text-muted'> Compartilhe algo com seus colegas, você é livre para criar suas conexões, desde que sejam verdadeiras!
                <br>  <br>
                <strong> Que tal postar conteúdos práticos e ajudar o próximo a avançar?</strong>
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light"> <a href="#">Petição</a></li>
                  <li class="list-group-item list-group-item-light"><a href="#">Anúncios</a></li>
                  <li class="list-group-item list-group-item-light"><a href="#">Calendários</a></li>
                  <li class="list-group-item list-group-item-light">Entre outros</li>
                </ul>
              </p>
            </div>
            {% else %}
            <div class="col-md-4">
              <div class="content-section">
                <h3>Venha postar algo com a gente!</h3>
                <p class='text-muted'> Suas postagens são abertas ao público, fique atento e publique com consciência!
                  <br> <br>
                  <strong> O que é possível fazer no site?</strong>
                  <ul class="list-group">
                    <li class="list-group-item list-group-item-light"> Postar conteúdos</li>
                    <li class="list-group-item list-group-item-light">Pesquisar conteúdos já postados</li>
                    <li class="list-group-item list-group-item-light">Criar sua petição</li>
                    <li class="list-group-item list-group-item-light">Alterar seu perfil</li>
                    <li class="list-group-item list-group-item-light">Entre outras possibilidades</li>
                  </ul>
                </p>
              </div>
            </div>            
            {% endif %}
          </div>
        </div>
      </main>
  
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>
</html>

application/templates/login.html
{%extends "layout.html"%}

<!---
Primeiro passo: from. acessar a instância do \
formulário que foi passado para o template,
Depois hidden_tag() vai ocultar e adicionar um\
token para proteger o usuário com base na key.

Segundo passo: Fieldset, será um conjunto de\
campos para o usuário; Legend, lengada para o 
formulário de registro;

Terceiro passo campo div irá guarda informações\
o nome do usuário, password, email, para imprimir\
Toda parte dentro do div está ligado ao form.py,\
sendo as variáveis aplicada ao caso.
form submit, btn btn-outline será um botão com contorno
azul que se aplica para as regras do bootstrap.
Div border vai criar na parte superior uma frase
com link mostrando o acesso ao login.
href vai acessar a parte da função def login,
por meio do url_for('login').



-->

{%block content%}

<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Acessar a Conta</legend>

      <div class="form-group">
        {{form.email.label(class="form-control-label")}} {% if form.email.errors
        %}
        <!---se o usuário digitar errado:-->
        {{form.email(class="form-control form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.email.errors%}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{form.email(class="form-control form-control-lg")}} {% endif
        %}
      </div>
      <div class="form-group">
        {{form.password.label(class="form-control-label")}} {% if
        form.password.errors %}
        <!---se o usuário digitar errado:-->
        {{form.password(class="form-control form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.password.errors%}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{form.password(class="form-control form-control-lg")}} {%
        endif %}
      </div>
      <div class="form-check">
        {{ form.remember(class="form-check-input") }} {{
        form.remember.label(class="form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group">
      {{form.submit(class="btn btn-outline-info")}}
      <small class="text-muted ml-2">
        <a href="{{url_for('users.reset_request')}}">Esqueceu a Senha?</a>
      </small>
    </div>
    
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Precisa de uma Conta?<a class="ml-2" href="{{ url_for('users.register')}}">
      Clique aqui</a
    >
  </small>
</div>


{%endblock content%}

application/templates/post.html
{%extends "layout.html"%}

{%block content%}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <deletesmall class="text-muted">{{ post.date_posted.strftime('%d-%m-%y- %H:%M') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-outline-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post', post_id=post.id)}}">Editar</a>
            <button type="button" class="btn btn-outline-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Excluir</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Excluir Postagem</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Você tem certeza que quer excluir essa postagem?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Sim">
          </form>
        </div>
      </div>
    </div>
  </div>

{%endblock%}

application/templates/posting.html
{%extends "layout.html"%} {%block content%}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">{{ legend }}</legend>
      <div class="form-group">
        {{form.title.label(class="form-control-label")}}
        {% if form.title.errors%}
        {{form.title(class="form-control form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.title.errors%}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} 
            {{form.title(class="form-control form-control-lg")}} 
        {% endif%}
      </div>
      <div class="form-group">
        <div class="text-justify">
        {{form.content.label(class="form-control-label")}} {% if
        form.content.errors %}
        <!---se o usuário digitar errado:-->
        {{form.content(class="form-control form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.content.errors %}
                <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} 
            {{form.content(class="form-control form-control-lg")}} 
        {%endif %}
        </div>
      </div>
    </fieldset>
    <div class="form-group">{{form.submit(class="btn btn-outline-info")}}</div>
  </form>
</div>

{%endblock%}

application/templates/request_reset_pass.html
{%extends "layout.html"%}

{%block content%}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Requisição Para Mudar Sua Senha</legend>

      <div class="form-group">
        {{form.email.label(class="form-control-label")}} {% if form.email.errors
        %}
        <!---se o usuário digitar errado:-->
        {{form.email(class="form-control form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.email.errors%}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{form.email(class="form-control form-control-lg")}} {% endif
        %}
      </div>
    </fieldset>
    <div class="form-group">
        {{form.submit(class="btn btn-outline-info")}}

    </div>
  </form>
</div>

{%endblock content%}

application/templates/reset_token.html
{%extends "layout.html"%}

{%block content%}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Alteração de Senha</legend>

      <div class="form-group">
        {{form.password.label(class="form-control-label")}} {% if
        form.password.errors %}
        <!---se o usuário digitar errado:-->
        {{form.password(class="form-control form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.password.errors%}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{form.password(class="form-control form-control-lg")}} {%
        endif %}
      </div>
      <div class="form-group">
        {{form.confirm_password.label(class="form-control-label")}} {% if
        form.confirm_password.errors %}
        <!---se o usuário digitar errado:-->
        {{form.confirm_password(class="form-control form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.confirm_password.errors%}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} 
        {{form.confirm_password(class="form-control form-control-lg")}} 
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">{{form.submit(class="btn btn-outline-info")}}</div>
  </form>
</div>

{%endblock content%}

application/templates/user_posts.html
{%extends "layout.html"%}

{%block content%}
  <h1 class="mb-3">Postagens  de {{user.username}} ({{posts.total}})</h1>
  {% for post in posts.items %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%y- %H:%M') }}</small>
      </div>
      <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  {%endfor %}
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}

    
{%endblock content%}